language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y fftw3-dev
  - sudo apt-get install -y liblapack-dev

script: ./autogen.sh && ./configure && make

notifications:
  irc: "irc.oftc.net#openvsip"

